# -*- coding: utf-8 -*-
"""download_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aUy5wUgU2YzvmdTfn8Se23c8oKiEwP8Z
"""

import kagglehub
import os
import sys

# Config
kaggle_DATASET_ID = "meowmeowmeowmeowmeow/gtsrb-german-traffic-sign"

def download_gtsrb(dataset_id):
  """
  Downloads the dataset using kagglehub library and returns the local path.
  """
  print(f"Attempting to download latest version of {dataset_id}...")
  try:
    path = kagglehub.dataset_download(dataset_id)

    print(f"Data is located in the kaggle cache at: {path}")
    return path
  except Exception as e:
    print("\n Error during Kagglehub download.")
    sys.exit(1)

if __name__ == "__main__":
  download_gtsrb(kaggle_DATASET_ID)